[control]
ansible-control-01 ansible_host=10.0.1.10

[docker_hosts]
docker-rocky-01  ansible_host=10.0.1.11 ansible_user=rocky    os_family=RedHat
docker-ubuntu-01 ansible_host=10.0.1.12 ansible_user=ubuntu   os_family=Debian

[docker_hosts:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args=-o StrictHostKeyChecking=accept-new
