---
- name: Apply hardened sysctls
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.d/99-cfg-hardening.conf
    reload: true
  loop: "{{ hardening_sysctl | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
